name: Lint

on:
  #pull_request:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main


jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: python3.10 -m pip install tox
      - name: Run tox
        run: python3.10 -m tox run