name: Run Tests

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.8"
            env: "py38"
          - python: "3.9"
            env: "py39"
          - python: "3.10"
            env: "py310"

    steps:
      - uses: actions/checkout@v3

      - name: Setup python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: pip install tox

      - name: Setup test environment
        run: tox run -e ${{ matrix.env }} --notest

      - name: Test with Tox
        run: tox run -e ${{ matrix.env }}-test

      - name: Setup lint environment
        run: python -m tox run -e ${{ matrix.env }}-lint --notest

      - name: Lint
        run: python -m tox run -e ${{ matrix.env }}-lint